### ISSUE TITLE
Trionyx enforces environment.json

### ISSUE THREAD

**Issue by casperfrx** [krukas/Trionyx#40]
Please consider using .env and os.getenv method instead of enforceing environment.json using your own defined get_env_var since you can not use true linux environment variables without either catching said errors in a monkey patch or altering the environment.json

Does not support loading safe environment variables in dynamic environments.

**Comment by krukas** [comment]
Thanks for the feedback, you mean using this https://pypi.org/project/python-dotenv/. Went for JSON because its easier to load with data types and structures. You can switch config dynamically by setting the TRIONYX_CONFIG env variable.

And the idea is that you never commit your <environment>.json, but that your deploy tool will generate it for your setup. This should be added and better explained in the documentation.

**Comment by casperfrx** [comment]
python-dotenv is the python implementation of a far more common use across code languages/frameworks using the .env file:
https://www.google.com/search?q=env+file

You've basically implemented the feature again and blocked out an proven and out of the box solution for passing environment variables.

The idea is of course also never to commit your .env file but provide a .env.example file that shows which environment variables are used and also which are mandatory or otherwise will be randomly generated / ignored (e.g. MYSQL_(USER|PASSWORD|DATABASE) or Django's SECRET_KEY).

**Comment by krukas** [comment]
I have looked more into .env file configuration. And its just another way for configuring your environment specific settings. Just like using json, yaml, ini or any other configuration file. Everything has its pros and cons, I understand the pros of using a .env file. But I like the pros of using a json or yaml more.

You can still use .env for you project by overriding these settings into your project settings.py file, and then you don't need an environment.json.

**Comment by casperfrx** [comment]
I am giving you as author the freedom to decide your architecture as you wish but here is my last argument:

yaml/yml and json files are config files. It's not surprisingly that docker-compose.yml, a yml config file, has a env_file field which allows you to specify an .env file (or whatever you named it). This makes a whole difference. Since environment variables are used to plug in environment specific variables which sometimes are not desired to be saved in console logs, like for example database logins, but also dynamically allows you to plug in variables in any deployment, being it build processes or the like. 

yaml and json configs files tend to be a lot more static, for example Google Cloud Platform service account json files or ansible yml files.

Config vs Environment variables.

**Comment by krukas** [comment]
If want to prevent leaking of your passwords, then you should definitely not use environment variables.  Because your environment variables are accessible to your whole process and all your child processes. So if any of those do debug logging or a crush dump reports, the change that this will include  environment variables is pretty high.

Looking at using an .env file:
- You still create a config file
- Format is limited to string values in key=value pair only
- Higher change of leaking your credentials to other processes and logs

Environment variables and/or using .env file has it uses. It’s really good for setting flags or paths, but I wouldn't use it for confidential information.
